import json
import logging
import os
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

logger = logging.getLogger("GoldRuleLoader")


@dataclass
class GoldRuleConfig:
    """Configurable weights and parameters derived from Hindsight Gold Rules."""

    # Captaincy Profiling
    captain_mid_multiplier: float = 1.15  # Boost for mid-priced (£6.0m-£9.0m) explosive assets
    captain_premium_bias_dampener: float = 0.95  # Dampens static price-only bias for premiums
    captain_easy_fdr_multiplier: float = 1.10  # Multiplier when captain has FDR <= 2
    captain_home_multiplier: float = 1.08  # Multiplier when captain is at Home

    # Hit Strategy & Transfer EV
    aggressive_hits_enabled: bool = True
    hit_hurdle_discount: float = 2.0  # Discount off -4 penalty when replacing underperformer with explosive
    horizon_hit_weight: float = 0.40  # Fraction of horizon gain credited to justify a hit
    max_hits_evaluated: int = 2  # Evaluate up to 2 hits when mathematically EV-positive

    # Formation & Budget Allocation
    midfield_formation_bonus: float = 0.75  # Soft bonus for heavy midfield formations (4-5-1, 3-5-2)
    budget_enabler_ppm_weight: float = 0.20  # Preference for budget enablers (< £6.0m) with high pts/£m

    # Metadata
    is_active: bool = False
    source_file: Optional[str] = None
    extracted_rules: List[Dict[str, Any]] = field(default_factory=list)


def load_gold_rule_config(path: str = "output/hindsight_gold_rules.json") -> GoldRuleConfig:
    """Safely loads and parses the Gold Rules JSON file generated by the Hindsight Optimization Engine.
    Falls back gracefully to default parameters if the file is not found or invalid.
    """
    if not os.path.exists(path):
        logger.warning(f"Gold rules file '{path}' not found. Using default baseline heuristics.")
        return GoldRuleConfig(is_active=False)

    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)

        rules = data.get("gold_rules", [])
        config = GoldRuleConfig(
            is_active=True,
            source_file=path,
            extracted_rules=rules,
        )

        for rule in rules:
            cat = rule.get("category")
            fv = rule.get("feature_values", {})

            # 1. Captaincy tuning
            if cat == "captain":
                prem_pct = fv.get("premium_captain_pct")
                if prem_pct is not None and prem_pct < 0.35:
                    # Low reliance on premiums -> reward explosive mid-priced assets
                    config.captain_mid_multiplier = 1.18
                    config.captain_premium_bias_dampener = 0.92

            # 2. Transfer / Hit tuning
            elif cat == "transfer":
                net_delta = fv.get("net_point_delta")
                if net_delta is not None and net_delta > 5.0:
                    config.aggressive_hits_enabled = True
                    config.hit_hurdle_discount = 2.0
                    config.horizon_hit_weight = 0.40

            # 3. Formation & Midfield Allocation
            elif cat == "position_allocation":
                mid_info = fv.get("MID", {})
                mid_share = mid_info.get("share_pct", 0.0)
                if mid_share >= 0.35:
                    config.midfield_formation_bonus = 0.85

            # 4. Budget & Price Efficiency
            elif cat == "price_efficiency":
                budget_info = fv.get("Budget (<£6.0m)", {})
                if budget_info and budget_info.get("pts_per_million", 0) > 2.0:
                    config.budget_enabler_ppm_weight = 0.25

        logger.info(
            f"Successfully loaded {len(rules)} Gold Rules from '{path}' (is_active=True)."
        )
        return config

    except Exception as e:
        logger.error(f"Error reading gold rules from '{path}': {e}. Falling back to defaults.")
        return GoldRuleConfig(is_active=False)
